import json, sys
sys.path.insert(0, '/home/derek/Projects/annotation-pipeline-skill')
from annotation_pipeline_skill.tools.validation import check_annotation_draft

task_id = 'v3_initial_deployment-000689'
payload = {
  "rows": [
    {"row_id": "unknown.jsonl_003453", "row_index": 0, "output": {"entities": {"technology": ["app", "PS4"]}, "json_structures": {}}},
    {"row_id": "unknown.jsonl_003454", "row_index": 1, "output": {"entities": {"document": ["packages/react-client/src/ReactFlightClient.js"], "event": ["Issue: [Flight] Look for moved debugInfo when logging component performance track (#34839)"], "project": ["facebook/react"], "technology": ["facebook", "react", "Flight", "ReactFlightClient.js"]}, "json_structures": {"task": ["Look for moved debugInfo when logging component performance track"]}}},
    {"row_id": "unknown.jsonl_003455", "row_index": 2, "output": {"entities": {"technology": ["Tair"]}, "json_structures": {"strategy": ["采取自主研发策略"]}}},
    {"row_id": "unknown.jsonl_003456", "row_index": 3, "output": {"entities": {"technology": ["Instagram"]}, "json_structures": {}}},
    {"row_id": "unknown.jsonl_003457", "row_index": 4, "output": {"entities": {"organization": ["Richard Petty Motorsports"], "person": ["Jones"], "time": ["October 21 , 2020"]}, "json_structures": {}}},
    {"row_id": "unknown.jsonl_003458", "row_index": 5, "output": {"entities": {"event": ["another lull"], "location": ["Ruweisat Ridge", "Tel El Eisa", "Miteirya Ridge"], "organization": ["Italian units"], "technology": ["Ultra"]}, "json_structures": {"status": ["another lull fell"]}}},
    {"row_id": "unknown.jsonl_003459", "row_index": 6, "output": {"entities": {"number": ["¥10万"], "time": ["本月"]}, "json_structures": {"reason": ["说明高价值客户留存策略奏效"], "status": ["本月ARR增量主要来自企业客户续约和套餐升级", "ARPU环比提升9%"], "task": ["计划主动触达所有合同金额超过¥10万的客户"]}}},
    {"row_id": "unknown.jsonl_003460", "row_index": 7, "output": {"entities": {"document": ["packages/react-dom-bindings/src/server/ReactFizzConfigDOM.js", "packages/react-dom-bindings/src/server/fizz-instruction-set/ReactDOMFizzInstructionSetInlineCodeStrings.js", "packages/react-dom-bindings/src/server/fizz-instruction-set/ReactDOMFizzInstructionSetShared.js", "packages/react-dom/src/__tests__/ReactDOMFizzStaticBrowser-test.js", "packages/react-dom/src/__tests__/ReactDOMFloat-test.js"], "event": ["Issue: [Fizz] Don't handle errors in completeBoundary instruction (#33073)"], "project": ["facebook/react"], "technology": ["facebook", "react", "Fizz", "completeBoundary", "errorDigest", "completeBoundaryWithStyles", "clientRenderBoundary", "$RX", "$RC"]}, "json_structures": {"decision": ["The first commit moves the client render logic inline into\n`completeBoundaryWithStyles`"], "status": ["Currently we're passing `errorDigest` to `completeBoundary` if there is\na client side error"]}}},
    {"row_id": "unknown.jsonl_003461", "row_index": 8, "output": {"entities": {"document": ["packages/react-client/src/forks/ReactFlightClientConfig.dom-bun.js", "packages/react-client/src/forks/ReactFlightClientConfig.dom-legacy.js", "packages/react-html/README.md", "packages/react-html/index.js", "packages/react-html/npm/index.js", "packages/react-html/npm/react-html.react-server.js", "packages/react-html/package.json", "packages/react-html/react-html.react-server.js", "packages/react-html/src/ReactHTMLLegacyClientStreamConfig.js", "packages/react-html/src/ReactHTMLServer.js", "packages/react-html/src/__tests__/ReactHTMLServer-test.js", "packages/react-server/src/forks/ReactFlightServerConfig.dom-legacy.js", "scripts/error-codes/codes.json", "scripts/rollup/bundles.js", "scripts/rollup/forks.js", "scripts/shared/inlinedHostConfigs.js"], "event": ["Issue: Add new package with renderToMarkup export (#30105)"], "person": ["Sebastian Silbermann"], "project": ["facebook/react", "react-html"], "technology": ["facebook", "react", "renderToMarkup", "renderToStaticMarkup", "useEffect", "useState", "renderToReadableStream", "Suspense", "preload()", "Fizz", "TextEncoder", "TextDecoder", "react-dom"]}, "json_structures": {"constraint": ["No useEffect, no useState etc. since it will never be\r\nhydrated", "You can't use any resource preloading like `preload()` from\r\n`react-dom`"], "goal": ["Add new package with renderToMarkup export"], "risk": ["large strings that use byteLengthOfChunk errors atm"], "technology": ["React Native", "Server Components", "Client Components", "Client References", "Flight Server"]}}},
    {"row_id": "unknown.jsonl_003462", "row_index": 9, "output": {"entities": {"event": ["The Ferals"], "location": ["Australian"], "organization": ["ABC"]}, "json_structures": {}}}
  ]
}

result = check_annotation_draft(task_id, payload)
print(json.dumps(result, indent=2))
